# Generated by Django 2.2.12 on 2020-09-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200730_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
